@startuml
participant Actor
Actor -> AnoLetivoController : createAndSaveAnoLetivo
activate AnoLetivoController
AnoLetivoController -> AnoLetivoService : createAndSaveAnoLetivo
activate AnoLetivoService
AnoLetivoService -> AnoLetivoDTOMapper : toModel
activate AnoLetivoDTOMapper
AnoLetivoDTOMapper -> AnoLetivoFactory : createAnoLetivo
activate AnoLetivoFactory
create AnoLetivo
AnoLetivoFactory -> AnoLetivo : new
activate AnoLetivo
AnoLetivo -> AnoLetivo : validate
activate AnoLetivo
AnoLetivo --> AnoLetivo
deactivate AnoLetivo
AnoLetivo --> AnoLetivoFactory
deactivate AnoLetivo
AnoLetivoFactory --> AnoLetivoDTOMapper
deactivate AnoLetivoFactory
AnoLetivoDTOMapper --> AnoLetivoService
deactivate AnoLetivoDTOMapper
AnoLetivoService -> AnoLetivoRepository : createAndSaveAnoLetivo
activate AnoLetivoRepository
AnoLetivoRepository -> AnoLetivoRepository : findById
activate AnoLetivoRepository
AnoLetivoRepository -> AnoLetivoJPAMapper : toModel
activate AnoLetivoJPAMapper
AnoLetivoJPAMapper -> AnoLetivoFactory : createAnoLetivo
activate AnoLetivoFactory
AnoLetivoFactory --> AnoLetivoJPAMapper
deactivate AnoLetivoFactory
AnoLetivoJPAMapper --> AnoLetivoRepository
deactivate AnoLetivoJPAMapper
AnoLetivoRepository --> AnoLetivoRepository
deactivate AnoLetivoRepository
create ErroGeralException
AnoLetivoRepository -> ErroGeralException : new
activate ErroGeralException
ErroGeralException --> AnoLetivoRepository
deactivate ErroGeralException
AnoLetivoRepository -> AnoLetivoJPAMapper : toJpa
activate AnoLetivoJPAMapper
create AnoLetivoJPA
AnoLetivoJPAMapper -> AnoLetivoJPA : new
activate AnoLetivoJPA
AnoLetivoJPA --> AnoLetivoJPAMapper
deactivate AnoLetivoJPA
AnoLetivoJPAMapper --> AnoLetivoRepository
deactivate AnoLetivoJPAMapper
AnoLetivoRepository -> AnoLetivoJPAMapper : toModel
activate AnoLetivoJPAMapper
AnoLetivoJPAMapper -> AnoLetivoFactory : createAnoLetivo
activate AnoLetivoFactory
create AnoLetivo
AnoLetivoFactory -> AnoLetivo : new
activate AnoLetivo
AnoLetivo --> AnoLetivoFactory
deactivate AnoLetivo
AnoLetivoFactory --> AnoLetivoJPAMapper
deactivate AnoLetivoFactory
AnoLetivoJPAMapper --> AnoLetivoRepository
deactivate AnoLetivoJPAMapper
AnoLetivoRepository --> AnoLetivoService
deactivate AnoLetivoRepository
AnoLetivoService -> AnoLetivoDTOMapper : toDTO
activate AnoLetivoDTOMapper
create AnoLetivoDTO
AnoLetivoDTOMapper -> AnoLetivoDTO : new
activate AnoLetivoDTO
AnoLetivoDTO --> AnoLetivoDTOMapper
deactivate AnoLetivoDTO
AnoLetivoDTOMapper --> AnoLetivoService
deactivate AnoLetivoDTOMapper
AnoLetivoService --> AnoLetivoController
deactivate AnoLetivoService
create ValidacaoInvalidaException
AnoLetivoController -> ValidacaoInvalidaException : new
activate ValidacaoInvalidaException
ValidacaoInvalidaException --> AnoLetivoController
deactivate ValidacaoInvalidaException
create ErroGeralException
AnoLetivoController -> ErroGeralException : new
activate ErroGeralException
ErroGeralException --> AnoLetivoController
deactivate ErroGeralException
return
@enduml