package com.grupo2.projeto.model.filter;

public enum QueryPresets
{
    EDICOESRUC("(SELECT PROPOSTA.ID FROM PROPOSTA WHERE (SELECT RUCID FROM EDICAOUC WHERE PROPOSTA.EDICAOUCID = EDICAOUC.ID) = ? AND PROPOSTA.ID = PROJETO.PROPOSTAID) = PROJETO.PROPOSTAID"),
    DOCENTEJURI("(SELECT AVALIACAO.IDPROJETO FROM AVALIACAO WHERE AVALIACAO.PRESIDENTEID = ? OR AVALIACAO.ORIENTADORID = ? OR AVALIACAO.ARGUENTEID = ?) = PROJETO.ID"),
    PROPOSTOSORGANIZACAO("(SELECT PROPOSTA.ID FROM PROPOSTA WHERE PROPOSTA.ORGANIZACAOID = ? AND PROPOSTA.ID = PROJETO.PROPOSTAID) = PROJETO.PROPOSTAID"),
    PROJETOCONCLUIDO("SELECT * FROM PROJETO WHERE ((SELECT COUNT(AVALIACAO.IDPROJETO) FROM AVALIACAO WHERE AVALIACAO.IDPROJETO = PROJETO.ID AND ESTADOAVALIACAO='CONCLUIDO') = (SELECT COUNT(AVALIACAO.IDPROJETO) FROM AVALIACAO WHERE AVALIACAO.IDPROJETO = PROJETO.ID))");

    private final String value;

    QueryPresets(String v)
    {
        this.value = v;
    }

    public String getValue()
    {
        return value;
    }
}
